<a href="https://colab.research.google.com/github/juanjmolina/Anal-tica-en-Recursos-Humanos/blob/main/a_exploracion.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#from google.colab import drive
#drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
#import sys
#import os
#path= '/content/drive/MyDrive/codigos/Analitica_Finanzas'
#os.chdir(path)
#sys.path.append(path+'/')

In [ ]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.metrics import mean_squared_error, mean_absolute_error, median_absolute_error
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression, Ridge, Lasso
from sklearn.ensemble import RandomForestRegressor, GradientBoostingRegressor
from sklearn.tree import DecisionTreeRegressor
from sklearn.svm import SVR
from sklearn.neighbors import KNeighborsRegressor
from sklearn.model_selection import train_test_split
from matplotlib.pyplot import figure

In [ ]:
import os
import sys

ruta =os.getcwd()
sys.path.append(ruta)

In [ ]:
import warnings
warnings.filterwarnings("ignore")

In [ ]:
# Leer el archivo CSV
df_historico = pd.read_csv("data/datos_historicos.csv")

In [ ]:
df_historico.head()

,ID,CreditScore,DebtRatio,Assets,Age,NumberOfDependents,NumberOfOpenCreditLinesAndLoans,MonthlyIncome,NumberOfTimesPastDue,EmploymentLength,HomeOwnership,Education,MaritalStatus,YearsAtCurrentAddress,NoPaidPerc
0,1,384,0.016560,37950,20,0,2,17355,9,28,Mortgage,Bachelor,Divorced,18,0.196566
1,2,516,0.138825,22909,46,5,8,7175,13,0,Rent,Bachelor,Married,9,0.264438
2,3,638,0.391149,126521,80,5,7,1910,6,25,Rent,Bachelor,Single,9,0.287568
3,4,363,0.463521,39543,54,9,0,19339,5,22,Own,High School,Widowed,3,0.181348
4,5,804,0.504824,38522,72,1,10,7928,18,19,Own,PhD,Married,5,0.343376

In [ ]:
# Calcular estadísticos descriptivos
## 'NumberOfTimesPastDue' Número de veces que el individuo ha tenido pagos atrasados
mean_past_due = df_historico['NumberOfTimesPastDue'].mean()
std_past_due = df_historico['NumberOfTimesPastDue'].std()
min_past_due = df_historico['NumberOfTimesPastDue'].min()
max_past_due = df_historico['NumberOfTimesPastDue'].max()
percentiles = df_historico['NumberOfTimesPastDue'].quantile([0.25, 0.5, 0.75])

In [ ]:
print(f"Promedio de pagos atrasados: {mean_past_due:.2f}")
print(f"Desviación estándar: {std_past_due:.2f}")
print(f"Valor mínimo: {min_past_due}")
print(f"Valor máximo: {max_past_due}")
print("Percentiles:")
print(percentiles)

Promedio de pagos atrasados: 9.49
Desviación estándar: 5.77
Valor mínimo: 0
Valor máximo: 19
Percentiles:
0.25     4.0
0.50    10.0
0.75    14.0
Name: NumberOfTimesPastDue, dtype: float64

In [ ]:
# Clasificación de riesgo basada en NumberOfTimesPastDue
def clasificar_riesgo(pagos_atrasados):
    if pagos_atrasados <= 4:
        return "Bajo riesgo"
    elif 5 <= pagos_atrasados <= 10:
        return "Riesgo medio"
    elif 11 <= pagos_atrasados <= 14:
        return "Riesgo alto"
    else:
        return "Riesgo muy alto"

In [ ]:
# Aplicar la clasificación al DataFrame
df_historico['Riesgo'] = df_historico['NumberOfTimesPastDue'].apply(clasificar_riesgo)

In [ ]:
# Mostrar los resultados de clasificación
print(df_historico['Riesgo'].value_counts())

Riesgo
Riesgo medio       2985
Bajo riesgo        2517
Riesgo muy alto    2465
Riesgo alto        2033
Name: count, dtype: int64

In [ ]:
df_historico.head(5)

,ID,CreditScore,DebtRatio,Assets,Age,NumberOfDependents,NumberOfOpenCreditLinesAndLoans,MonthlyIncome,NumberOfTimesPastDue,EmploymentLength,HomeOwnership,Education,MaritalStatus,YearsAtCurrentAddress,NoPaidPerc,Riesgo
0,1,384,0.016560,37950,20,0,2,17355,9,28,Mortgage,Bachelor,Divorced,18,0.196566,Riesgo medio
1,2,516,0.138825,22909,46,5,8,7175,13,0,Rent,Bachelor,Married,9,0.264438,Riesgo alto
2,3,638,0.391149,126521,80,5,7,1910,6,25,Rent,Bachelor,Single,9,0.287568,Riesgo medio
3,4,363,0.463521,39543,54,9,0,19339,5,22,Own,High School,Widowed,3,0.181348,Riesgo medio
4,5,804,0.504824,38522,72,1,10,7928,18,19,Own,PhD,Married,5,0.343376,Riesgo muy alto

In [ ]:
# Guardar el DataFrame con la nueva columna 'Riesgo' en un archivo CSV
df_historico.to_csv("data/datos_historicos_clasificados.csv", index=False)